sudo: required
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
services:
  - docker
stages:
  - verify
  - test
  - publish
before_install:
  - npm i -g npx babel-cli
jobs:
  include:
    - stage: verify
      script:
        - lerna run build
    - stage: test
      script:
        - lerna run test
    - stage: publish
      script:
        - lerna run publish