sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - npm i -g npx
script:
  - lerna bootstrap
  - lerna run build
  - lerna run test
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      git checkout ${TRAVIS_BRANCH};
      git reset --hard ${TRAVIS_COMMIT};
      lerna bootstrap;
      lerna run build;
      git remote set-url origin ${CIVAR_GH_REPOSITORY_URL};
      printf -- "//registry.npmjs.org/:_authToken=${CIVAR_NPM_TOKEN}" > ./packages/node-boilerplate-middleware/.npmrc;
      LERNA_CD_VERSION='patch';
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        COMMIT_MESSAGE="$(cat ./.commit_message)";
        if [ -z "${COMMIT_MESSAGE##*"[major release]"*}" ]; then
          LERNA_CD_VERSION='major';
        elif [ -z "${COMMIT_MESSAGE##*"[minor release]"*}" ]; then
          LERNA_CD_VERSION='minor';
        fi;
        lerna publish --registry=https://registry.npmjs.org/ --yes --cd-version "${LERNA_CD_VERSION}";
      fi;
    fi;
