sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - npm i -g npx
script:
  - lerna bootstrap
  - lerna run build
  - lerna run test
  - printf -- "https://registry.npmjs.org//:_authToken=${CIVAR_NPM_TOKEN}" > ./packages/node-boilerplate-middleware/.npmrc
  - lerna publish
