sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - nvm use 6 && npm i -g npx
  - nvm use 8 && npm i -g npx
script:
  - lerna bootstrap
  - lerna run build
  - nvm use 6 && lerna run test
  - nvm use 8 && lerna run test
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
      git checkout ${TRAVIS_BRANCH};
      git reset --hard ${TRAVIS_COMMIT};
      lerna bootstrap;
      lerna run build;
      git remote set-url origin ${CIVAR_GH_REPOSITORY_URL};
      printf -- "//registry.npmjs.org/:_authToken=${CIVAR_NPM_TOKEN}" > ./packages/server-boilerplate-middleware/.npmrc;
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        if [ -z "${TRAVIS_COMMIT_MESSAGE##*"[major release]"*}" ]; then
          LERNA_CD_VERSION='major';
        elif [ -z "${TRAVIS_COMMIT_MESSAGE##*"[minor release]"*}" ]; then
          LERNA_CD_VERSION='minor';
        else
          LERNA_CD_VERSION='patch';
        fi;
        lerna publish --yes --cd-version "${LERNA_CD_VERSION}";
      fi;
    fi;
