sudo: required
language: node_js
node_js:
  - "iojs"
  - "6"
  - "7"
  - "8"
services:
  - docker
stages:
  - verify
  - publish
jobs:
  include:
    - stage: verify
      script:
        - lerna run build
        - lerna run test
    - stage: publish
      script: ./test 2